### ISSUE TITLE
Quarto Pub Credentials

### ISSUE THREAD

**Issue by Julenasti** [Pakillo/quarto-course-website-template#1]
Hi Paco,

This morning I tried your template and it is very nice and easy to use. Thanks for making it public!

I wanted to publish in quarto pub though (https://quarto.org/docs/publishing/quarto-pub.html) and I was having a problem with authorising quarto pub credentials (https://quarto.org/docs/publishing/quarto-pub.html#quarto-pub-credentials). I guess it's similar to what you have created with the github pages. So my question is, once you add the repository’s action Secrets, did it work well for you?

I based my template on yours (https://github.com/Julenasti/curso-git-github-r), but I created a new one for mine because I wanted to see how it worked from scratch (https://julenasti.quarto.pub/curso-git-github-r/). Compared to yours, mine has another target in the github actions to be able to publish in quarto-pub:
```
with:
          target: quarto-pub
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}
```

Thanks in advance,

**Comment by Pakillo** [comment]
Hi Julen, 

I haven't published with quarto.pub yet so I can't answer your questions. I guess it should work if you follow the steps here https://quarto.org/docs/publishing/quarto-pub.html#quarto-pub-credentials? Otherwise you could host the website on GitHub? Or render the website locally in your computer and upload the output rather than using GitHub Actions for automatic rendering

**Comment by Julenasti** [comment]
Thanks Paco! Yes, I followed those steps (or at least I tried) but I got a message that I didn't have the authorisation. I guess this has to be something to do with the actions secret and I thought you might have done this step also to host the website on GitHub changing the target. Yes, as you said, it's not a big deal because I can render locally without problem and upload but I was wondering how to do it with github actions. I will inspect more 🔍

**Comment by Pakillo** [comment]
Ok. It worked straightforward for me on github because I already have it configured (tokens and all). If you can't get quarto.pub to work you may still be able to render automatically and host on github pages. Or just render locally. Anyway, at least you have a running website!
